"use client"
// import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { NearContext, Wallet } from "@/wallets/WalletSelector";
import { WalletProvider } from "@/providers/WalletProvider";
import { useEffect, useState } from "react";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const wallet = new Wallet({ createAccessKeyFor: "minsta.mintspace2.testnet", networkId: "testnet" });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const [signedAccountId, setSignedAccountId] = useState('');

  // useEffect(() => {
  //   wallet.startUp(setSignedAccountId);
  // }, []);

  return (
    // <WalletProvider>
    <html lang="en">
      {/* <NearContext.Provider value={{ wallet, signedAccountId }}> */}
      <body className={inter.className}>{children}</body>
      {/* </NearContext.Provider> */}
    </html>
    // </WalletProvider>
  );
}
